# Generated by Django 4.1.6 on 2023-03-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_alter_customer_address_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer',
        ),
    ]
